/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package thucthi;

import Class.KhuyenMai;
import ClassThucthi.ConnectedDatabase;
import ClassThucthi.Themdatabase;
import coffee.ListKhuyenMai;
import static coffee.ListKhuyenMai.Panel;
import coffee.ListNhanVien;
import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author boss
 */
public class InsertKhuyenMai extends javax.swing.JPanel {

    /**
     * Creates new form InsertKhuyenMai
     */
    public InsertKhuyenMai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        ngaybd = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtngaybd = new javax.swing.JTextField();
        txtngaykt = new javax.swing.JTextField();
        txtht = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        close = new javax.swing.JButton();

        jButton1.setText("jButton1");

        ngaybd.setText("Ngày bắt đầu");

        jLabel2.setText("Ngày kết thúc");

        jLabel3.setText("Giảm(%)");

        jLabel4.setText("Tên khuyến mãi");

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        close.setText("CLOSE");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ngaybd, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtngaybd)
                        .addComponent(txtngaykt)
                        .addComponent(txtht)
                        .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                    .addComponent(close))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngaybd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtngaybd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtngaykt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok)
                    .addComponent(close))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
      ListKhuyenMai.Panel.removeAll();
      ListKhuyenMai.Panel.add(new JPanel());
      ListKhuyenMai.Panel.validate();
    }//GEN-LAST:event_closeActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
       Date date1=Date.valueOf(txtngaybd.getText());
      Date date2=Date.valueOf(txtngaykt.getText());
      int pt=Integer.parseInt(txtht.getText());
        if(txtngaybd.getText().equals("")||txtngaykt.getText().equals("")
               ||txtname.getText().equals("")||txtht.getText().equals("")){
           JOptionPane.showMessageDialog(this,"Bạn chưa nhập đủ thông tin khuyến mãi!!!!");
       }
      
       else if((date2.getTime()-date1.getTime())<0){
               JOptionPane.showMessageDialog(this,"Lỗi: Ngày kết thúc trước ngày bắt đầu");
               }
       else if(pt>=100){
           JOptionPane.showMessageDialog(this,"Giảm giá quá mức cho phép");
       }
               
               else{    
       try{
          KhuyenMai km=new KhuyenMai();
          km.setDatestart(Date.valueOf(txtngaybd.getText()));
          km.setDateend(Date.valueOf(txtngaykt.getText()));
          km.setPercent(Integer.parseInt(txtht.getText()));
          km.setContains(txtname.getText());
          Themdatabase td=new Themdatabase();
          int k=td.themDiscount(km);
           if(k>0)JOptionPane.showMessageDialog(this,"Thêm thành công "+txtname.getText());
           txtngaybd.setText("");
           txtngaykt.setText("");
           txtht.setText("");
           txtname.setText("");
           DefaultTableModel model=(DefaultTableModel) coffee.ListKhuyenMai.jTable1.getModel();
           model.setRowCount(0);
            String sql=null;
        Connection cnn=ConnectedDatabase.getConnection();
          sql="select * from discount";
        try {
          Statement  ptm= cnn.createStatement();
            ResultSet rs=ptm.executeQuery(sql);
            while(rs.next()){
                int no=rs.getInt("no");
                Date datestart=rs.getDate("datestart");
                Date dateend=rs.getDate("dateend");
                int percent=rs.getInt("percent");
                String contains=rs.getString("contains");
                Object []data={no,datestart,dateend,percent,contains};
                
                model.addRow(data);
                
            }
            
        } catch (SQLException ex) {
            ListNhanVien list1=new ListNhanVien();
           JOptionPane.showMessageDialog(list1,"lỗi"+ ex);
        }
       }catch(Exception ex){
            JOptionPane.showMessageDialog(this,"Lỗi: "+ex);
       }
               }
    }//GEN-LAST:event_okActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton close;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel ngaybd;
    private javax.swing.JButton ok;
    private javax.swing.JTextField txtht;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtngaybd;
    private javax.swing.JTextField txtngaykt;
    // End of variables declaration//GEN-END:variables
}
