package employeePackage;
import model.*;

import static java.lang.Class.forName;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class LogIn extends javax.swing.JFrame {
public static String saveIdString;
public static String saveUsernameString;
public static User user;
public static    PreparedStatement stm;
    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
         Clock();
      
    }
public  static LogIn a = new LogIn();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        usernameL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        loginBL = new javax.swing.JButton();
        clearBL = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        passwordL = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng Nhập Hệ Thống Quản Lý Cà Phê");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(150, 80));
        setMaximizedBounds(new java.awt.Rectangle(300, 200, 0, 0));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1980, 1208));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-470, 0, 1100, 280));

        jLabel1.setText("Tên đăng nhập:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, -1, -1));

        usernameL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameLActionPerformed(evt);
            }
        });
        jPanel1.add(usernameL, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 340, 30));

        jLabel2.setText("Mật khẩu:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        loginBL.setText("Đăng Nhập");
        loginBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBLActionPerformed(evt);
            }
        });
        jPanel1.add(loginBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, 340, -1));

        clearBL.setText("Xóa");
        clearBL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBLActionPerformed(evt);
            }
        });
        jPanel1.add(clearBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 140, -1));

        jButton3.setText("Quên mật khẩu");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 130, -1));

        jTextField2.setEditable(false);
        jTextField2.setBorder(null);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, 250, 30));
        jPanel1.add(passwordL, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 340, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1044, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameLActionPerformed

    private void clearBLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBLActionPerformed
       usernameL.setText("");
       passwordL.setText("");
    }//GEN-LAST:event_clearBLActionPerformed

    private void loginBLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBLActionPerformed
                      login();       
                   
    }//GEN-LAST:event_loginBLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void aa() {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               a.setVisible(true);
               
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton clearBL;
    public static javax.swing.JButton jButton3;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public javax.swing.JTextField jTextField2;
    public static javax.swing.JButton loginBL;
    public javax.swing.JPasswordField passwordL;
    public javax.swing.JTextField usernameL;
    // End of variables declaration//GEN-END:variables
    public  void login(){
        try{
            usernameL.setText("E001");
            passwordL.setText("1");
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection(Main.url, Main.usernameSQL, Main.passwordSQL);
           String sql = "SELECT * FROM employees WHERE username =? AND password = ?";
                       stm = con.prepareStatement(sql);
			stm.setString(1, usernameL.getText());
			stm.setString(2, passwordL.getText());
			ResultSet rs = stm.executeQuery();
                        if(rs.next()){
                            saveIdString = rs.getString(1);
                            saveUsernameString = rs.getString(2);
                            user = new User(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7));
                            char checkJobtitle = saveIdString.charAt(0);
                            if(Character.toString(checkJobtitle).compareTo("E")==0){
                            
                    EmployeeTask et = new EmployeeTask();
                    et.e();
                            
                            a.setVisible(false);
                            }
                        
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "Đăng nhập không thành công.");
                        }
                        
            
        
        
        
        con.close();
        
        
        }catch(Exception e){
            
        e.printStackTrace();}
        
    }

public void Clock(){
    
    Thread clock = new Thread(){
              public void run(){
            try{
        while (true) {            
            java.util.Date date = new java.util.Date();
            DateFormat df = new SimpleDateFormat("hh:mm:ss  EEEE ,dd/MM/yyyy");
	    String time = df.format(date);
             jTextField2.setText(time);
            
        }
    
    }
            catch(Exception e){
                e.printStackTrace();
            }
        }
    };clock.start();
    
}    


}
